### ISSUE TITLE
Use @expo/batcher for batch inserts

### ISSUE THREAD

**Issue by wschurman** [expo/entity#99]
Documenting this for posterity, but after investigating it looks like we probably won't want to use it for general-purpose mutations in entity.

### Background

Let's say we have an entity with one integer field, backed by a postgres DB with a unique constraint on the column. Batch inserting is something that isn't very well supported by entity as it would need to run N inserts to insert N items into the same table.

The following efficient query would be far less efficient expressed in entity code:
```sql
INSERT INTO blah_table (num) VALUES (1), (2), (3), (4) RETURNING *;
```
Entity equivalent:
```typescript
const numsToInsert = [1..4];
const results = await Promise.all(numsToInsert.map(n => TEntity.creator(vc).setField('num', n).enforceCreateAsync()));
```
which translates to (in parallel):
```sql
INSERT INTO blah_table (num) VALUES (1) RETURNING *;
INSERT INTO blah_table (num) VALUES (2) RETURNING *;
INSERT INTO blah_table (num) VALUES (3) RETURNING *;
INSERT INTO blah_table (num) VALUES (4) RETURNING *;
```

### Hypothesis

We can use https://www.npmjs.com/package/@expo/batcher to coalesce inserts into the DB. That way, the example above could translate into the first query automatically if all the entity writes are executed in a short enough period of time for batcher's batch.

### Conclusion

Batcher's error handling doesn't quite work for our case. Let's say a row existed in the able with `num = 3` and we tried to insert a batch: `INSERT INTO blah_table (num) VALUES (1), (2), (3), (4) RETURNING *;`. This whole query would fail, so all the batch items would fail. This could cause some unintended consequences in entity if we're inserting multiple entities of the same type from very code locations at the same time (same batch). It would mean that there could be a side-effect where a failure to insert one entity in codepath A could cause a failure to insert an entity for codepath B even if A and B are supposed to be independent.

**Comment by wschurman** [comment]
cc @ide for reference

**Comment by ide** [comment]
The error handling has to work this way, I think. I'm not sure there's a clean way to do a batch insertion and get back an array of results from Postgres unless we write a query with `ON CONFLICT` perhaps. This said, I'd still think that batched insertions could work -- we already need to handle insertion failures due to external reasons (ex: database crash).

**Comment by wschurman** [comment]
> This said, I'd still think that batched insertions could work -- we already need to handle insertion failures due to external reasons (ex: database crash).

Yep, but what we don't want is interaction between the following two cases, which a batcher could theoretically create:
Callsite A:
```typescript
function createBlahIfNotExists(num: number): Promise<BlahEntity> {
  // tries to create entity with num = num.
  try {
    return await BlahEntity.creator(vc).setField('num', num).enforceCreateAsync();
  } catch (e) {
    return await BlahEntity.loader(vc).loadByField('num', num);
  }
}
```

Callsite B:
```typescript
function createRandomBlah(): Promise<BlahEntity> {
  // should always succeed because num is sufficiently random or something like that
  return await BlahEntity.creator(vc).setField('num', rand(0, INF)).enforceCreateAsync();
}
```

If both of these were to be batched, the call within `createRandomBlah` could potentially fail since the call within `createBlahIfNotExists` is expected to fail more often. The two should be independent.

The other thing I noticed while investigating this is that all transactions would need to have their own batcher (so that insert queries could be run inside a transaction), and because all inserts are wrapped in their own transactions if one isn't passed in, the end effect of adding batcher would be minimal.

**Comment by ide** [comment]
That makes sense - I wasn't considering try-catch scenarios where we expect there to be errors.
